### ISSUE TITLE
Tile size

### ISSUE THREAD

**Issue by webmap2015** [Raruto/tile-proxy-php#1]
I only changed config.php file,
```
$config['bbox'] = '-180,-90,180,90'.
```
Other files are same. Tiles are cached, but sizes are 0 byte.

![image](https://user-images.githubusercontent.com/10267317/76657620-4de20280-6583-11ea-907d-98695ecfa178.png)

**Comment by Raruto** [comment]
Are there any issues with default settings?
It's curl properly enabled? Did you also tried it on a actual server?

**Comment by Raruto** [comment]
```php
$config['bbox'] = '-180,-90,180,90'; // <-- NB it must end with semicolon, not a "dot"
```

**Comment by webmap2015** [comment]
Yes, it ends with semicolon (;) and php curl enabled.

![image](https://user-images.githubusercontent.com/10267317/76663106-0e221780-6591-11ea-9a57-b4b3e263011f.png)

"mod_rewrite" enabled.

![image](https://user-images.githubusercontent.com/10267317/76663402-d8c9f980-6591-11ea-92e3-a521e325d7fe.png)

htaccess support

![image](https://user-images.githubusercontent.com/10267317/76664660-25173880-6596-11ea-8121-5a7ee7dbf91a.png)


I tried with "wampserver3.2.0_x64" and "xampp-windows-x64-7.4.3-0-VC15-installer".

Same problem continues.

**Comment by webmap2015** [comment]
Hi, now, I re-download "tile-prox-php and add to WAMP Server, I don't change any files.

Result

![image](https://user-images.githubusercontent.com/10267317/76677525-5ddbff80-65e0-11ea-821f-d0353d5bf49d.png)
**********************************************************************
![image](https://user-images.githubusercontent.com/10267317/76677519-5288d400-65e0-11ea-90c1-1583a85bcf8e.png)
**********************************************************************
![image](https://user-images.githubusercontent.com/10267317/76677527-6cc2b200-65e0-11ea-8c15-d2dd7310e50f.png)

**Comment by webmap2015** [comment]
"index.php" file result.

![image](https://user-images.githubusercontent.com/10267317/76680633-3f373200-65fb-11ea-97b2-e624ce128a0f.png)

******************************************************************************************************
******************************************************************************************************
![image](https://user-images.githubusercontent.com/10267317/76682200-2afb3100-660b-11ea-99b1-56872cc93f4a.png)
******************************************************************************************************
******************************************************************************************************
"config.php" file result.

![image](https://user-images.githubusercontent.com/10267317/76680663-79a0cf00-65fb-11ea-9442-3da458324710.png)

**Comment by Raruto** [comment]
This call is OK:

```
localhost/tile-proxy-php-master/index.php
```
see [index.php#L44](https://github.com/Raruto/tile-proxy-php/blob/742431ecfddbe51e2b752c0e49ce34346ed87ba4/index.php#L44) for more info.

---

These are also correct calls:

```
localhost/tile-proxy-php-master/index.php?r=osm&z=0&x=0&y=0
```
```
localhost/tile-proxy-php-master/osm/0/0/0.png
```

The mere fact that curl is installed on localhost does not mean that it can work properly (eg there may be problems with your firewal, missing ssl certificates, and many other things ..)

In order not to go crazy, you can first test it on a "real" server and then try to investigate what happens to your local server when executing this function.

https://github.com/Raruto/tile-proxy-php/blob/742431ecfddbe51e2b752c0e49ce34346ed87ba4/index.php#L188

**Comment by webmap2015** [comment]
Ubuntu 18.04 Virtual Machine result

![image](https://user-images.githubusercontent.com/10267317/76685967-d666ae80-6628-11ea-9df9-7a71cf0b58d5.png)

**Comment by webmap2015** [comment]
Hi, I tried on Windows. Now, on fresh Ubuntu 18.04 Virtual Machine, problem continues.

![image](https://user-images.githubusercontent.com/10267317/76685999-1af24a00-6629-11ea-8f8d-cbff44446391.png)

**Comment by webmap2015** [comment]
But, remote file working good.

![image](https://user-images.githubusercontent.com/10267317/76686296-702f5b00-662b-11ea-94d3-2b3850ec36c1.png)

**Comment by webmap2015** [comment]
When I first run "tile-proxy-php", there are http debugger logs.

![image](https://user-images.githubusercontent.com/10267317/76686598-b5ed2300-662d-11ea-8ae8-067c8c233e19.png)

**Comment by Raruto** [comment]
> But, remote file working good.

As i said, this is definitely a curl [related issue](https://stackoverflow.com/questions/34036579/curl-image-using-php-but-empty-file-is-created), also try to take a look at [this](https://wiki.openstreetmap.org/wiki/ProxySimplePHP5) type of solution to check it..

---

As I said before, the gist of your problem is within this function:

https://github.com/Raruto/tile-proxy-php/blob/742431ecfddbe51e2b752c0e49ce34346ed87ba4/index.php#L188

Try to debug it a bit to better understand (more info: [here](https://www.php.net/manual/en/function.curl-error.php)).

**Comment by webmap2015** [comment]
Hi,

![image](https://user-images.githubusercontent.com/10267317/76709792-a1368b00-6712-11ea-9b19-c87c133cf2ff.png)

**Comment by Raruto** [comment]
These urls should work except [openstreetmap.org](https://operations.osmfoundation.org/policies/tiles/):

```php
$url = 'https://a.tile.openstreetmap.org/10/520/377.png';
$url = 'https://a.tile.opentopomap.org/10/520/377.png';
$url = 'https://a.tile.openstreetmap.fr/osmfr/10/520/377.png';

$ch = curl_init( $url );

curl_setopt( $ch, CURLOPT_FOLLOWLOCATION, true );
curl_setopt( $ch, CURLOPT_HEADER, 0 );

//Required for http(s)
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

//Required to be true
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_BINARYTRANSFER,1);

// UPDATE (2020): https://operations.osmfoundation.org/policies/tiles/
// curl_setopt( $ch, CURLOPT_USERAGENT, 'App Name example@example.com' );
// curl_setopt( $ch, CURLOPT_REFERER, true );

$result = curl_exec( $ch );

// var_dump( curl_error($ch) );

curl_close( $ch );

header ('Content-Type: image/png');

echo $result;
```

This is a problem common to other applications, you have to add certain headers to get it working again (let me know if you can find a solution...)

**Comment by Raruto** [comment]
For example, something like the following should be OK:

```php
curl_setopt( $ch, CURLOPT_USERAGENT, 'MyTestApp/0.1 (+info@example.com)' );
```

**NB** fix it properly on your production server
